// Auto-generated by generate_registration.py — do not edit
#include <essentia/algorithmfactory.h>

#include "algorithms/complex/cartesiantopolar.h"
#include "algorithms/complex/magnitude.h"
#include "algorithms/complex/polartocartesian.h"
#include "algorithms/filters/allpass.h"
#include "algorithms/filters/bandpass.h"
#include "algorithms/filters/bandreject.h"
#include "algorithms/filters/dcremoval.h"
#include "algorithms/filters/equalloudness.h"
#include "algorithms/filters/highpass.h"
#include "algorithms/filters/iir.h"
#include "algorithms/filters/lowpass.h"
#include "algorithms/filters/medianfilter.h"
#include "algorithms/filters/movingaverage.h"
#include "algorithms/rhythm/beatsloudness.h"
#include "algorithms/rhythm/beattrackerdegara.h"
#include "algorithms/rhythm/beattrackermultifeature.h"
#include "algorithms/rhythm/bpmhistogram.h"
#include "algorithms/rhythm/bpmhistogramdescriptors.h"
#include "algorithms/rhythm/bpmrubato.h"
#include "algorithms/rhythm/harmonicbpm.h"
#include "algorithms/rhythm/loopbpmconfidence.h"
#include "algorithms/rhythm/loopbpmestimator.h"
#include "algorithms/rhythm/noveltycurve.h"
#include "algorithms/rhythm/noveltycurvefixedbpmestimator.h"
#include "algorithms/rhythm/onsetdetection.h"
#include "algorithms/rhythm/onsetdetectionglobal.h"
#include "algorithms/rhythm/onsetrate.h"
#include "algorithms/rhythm/onsets.h"
#include "algorithms/rhythm/percivalbpmestimator.h"
#include "algorithms/rhythm/percivalenhanceharmonics.h"
#include "algorithms/rhythm/percivalevaluatepulsetrains.h"
#include "algorithms/rhythm/rhythmextractor.h"
#include "algorithms/rhythm/rhythmextractor2013.h"
#include "algorithms/rhythm/rhythmtransform.h"
#include "algorithms/rhythm/singlebeatloudness.h"
#include "algorithms/rhythm/superfluxextractor.h"
#include "algorithms/rhythm/superfluxnovelty.h"
#include "algorithms/rhythm/superfluxpeaks.h"
#include "algorithms/rhythm/temposcalebands.h"
#include "algorithms/rhythm/tempotap.h"
#include "algorithms/rhythm/tempotapdegara.h"
#include "algorithms/rhythm/tempotapmaxagreement.h"
#include "algorithms/rhythm/tempotapticks.h"
#include "algorithms/spectral/barkbands.h"
#include "algorithms/spectral/bfcc.h"
#include "algorithms/spectral/energyband.h"
#include "algorithms/spectral/energybandratio.h"
#include "algorithms/spectral/erbbands.h"
#include "algorithms/spectral/flatnessdb.h"
#include "algorithms/spectral/flux.h"
#include "algorithms/spectral/frequencybands.h"
#include "algorithms/spectral/gfcc.h"
#include "algorithms/spectral/hfc.h"
#include "algorithms/spectral/hpcp.h"
#include "algorithms/spectral/logspectrum.h"
#include "algorithms/spectral/maxmagfreq.h"
#include "algorithms/spectral/melbands.h"
#include "algorithms/spectral/mfcc.h"
#include "algorithms/spectral/panning.h"
#include "algorithms/spectral/rolloff.h"
#include "algorithms/spectral/spectralcentroidtime.h"
#include "algorithms/spectral/spectralcomplexity.h"
#include "algorithms/spectral/spectralcontrast.h"
#include "algorithms/spectral/spectralpeaks.h"
#include "algorithms/spectral/spectralwhitening.h"
#include "algorithms/spectral/spectrumtocent.h"
#include "algorithms/spectral/strongpeak.h"
#include "algorithms/spectral/triangularbands.h"
#include "algorithms/spectral/triangularbarkbands.h"
#include "algorithms/standard/autocorrelation.h"
#include "algorithms/standard/binaryoperator.h"
#include "algorithms/standard/binaryoperatorstream.h"
#include "algorithms/standard/bpf.h"
#include "algorithms/standard/chromagram.h"
#include "algorithms/standard/clipper.h"
#include "algorithms/standard/constantq.h"
#include "algorithms/standard/crosscorrelation.h"
#include "algorithms/standard/cubicspline.h"
#include "algorithms/standard/dct.h"
#include "algorithms/standard/derivative.h"
#include "algorithms/standard/envelope.h"
#include "algorithms/standard/fftk.h"
#include "algorithms/standard/fftkcomplex.h"
#include "algorithms/standard/framebuffer.h"
#include "algorithms/standard/framecutter.h"
#include "algorithms/standard/frametoreal.h"
#include "algorithms/standard/idct.h"
#include "algorithms/standard/ifftk.h"
#include "algorithms/standard/ifftkcomplex.h"
#include "algorithms/standard/maxfilter.h"
#include "algorithms/standard/minmax.h"
#include "algorithms/standard/monomixer.h"
#include "algorithms/standard/multiplexer.h"
#include "algorithms/standard/noiseadder.h"
#include "algorithms/standard/nsgconstantq.h"
#include "algorithms/standard/nsgiconstantq.h"
#include "algorithms/standard/overlapadd.h"
#include "algorithms/standard/peakdetection.h"
#include "algorithms/standard/powerspectrum.h"
#include "algorithms/standard/realaccumulator.h"
#include "algorithms/standard/replaygain.h"
#include "algorithms/standard/resample.h"
#include "algorithms/standard/scale.h"
#include "algorithms/standard/silencerate.h"
#include "algorithms/standard/slicer.h"
#include "algorithms/standard/spectrum.h"
#include "algorithms/standard/spectrumCQ.h"
#include "algorithms/standard/spline.h"
#include "algorithms/standard/startstopsilence.h"
#include "algorithms/standard/stereodemuxer.h"
#include "algorithms/standard/stereomuxer.h"
#include "algorithms/standard/stereotrimmer.h"
#include "algorithms/standard/trimmer.h"
#include "algorithms/standard/unaryoperator.h"
#include "algorithms/standard/unaryoperatorstream.h"
#include "algorithms/standard/vectorrealaccumulator.h"
#include "algorithms/standard/viterbi.h"
#include "algorithms/standard/warpedautocorrelation.h"
#include "algorithms/standard/welch.h"
#include "algorithms/standard/windowing.h"
#include "algorithms/stats/centralmoments.h"
#include "algorithms/stats/centroid.h"
#include "algorithms/stats/crest.h"
#include "algorithms/stats/decrease.h"
#include "algorithms/stats/distributionshape.h"
#include "algorithms/stats/energy.h"
#include "algorithms/stats/entropy.h"
#include "algorithms/stats/flatness.h"
#include "algorithms/stats/geometricmean.h"
#include "algorithms/stats/histogram.h"
#include "algorithms/stats/instantpower.h"
#include "algorithms/stats/mean.h"
#include "algorithms/stats/median.h"
#include "algorithms/stats/poolaggregator.h"
#include "algorithms/stats/powermean.h"
#include "algorithms/stats/rawmoments.h"
#include "algorithms/stats/rms.h"
#include "algorithms/stats/singlegaussian.h"
#include "algorithms/stats/variance.h"
#include "algorithms/temporal/duration.h"
#include "algorithms/temporal/effectiveduration.h"
#include "algorithms/temporal/larm.h"
#include "algorithms/temporal/leq.h"
#include "algorithms/temporal/loudness.h"
#include "algorithms/temporal/loudnessebur128.h"
#include "algorithms/temporal/loudnessebur128filter.h"
#include "algorithms/temporal/loudnessvickers.h"
#include "algorithms/temporal/lpc.h"
#include "algorithms/temporal/zerocrossingrate.h"
#include "algorithms/tonal/audio2midi.h"
#include "algorithms/tonal/audio2pitch.h"
#include "algorithms/tonal/chordsdescriptors.h"
#include "algorithms/tonal/chordsdetection.h"
#include "algorithms/tonal/chordsdetectionbeats.h"
#include "algorithms/tonal/dissonance.h"
#include "algorithms/tonal/harmonicpeaks.h"
#include "algorithms/tonal/highresolutionfeatures.h"
#include "algorithms/tonal/inharmonicity.h"
#include "algorithms/tonal/key.h"
#include "algorithms/tonal/multipitchklapuri.h"
#include "algorithms/tonal/multipitchmelodia.h"
#include "algorithms/tonal/oddtoevenharmonicenergyratio.h"
#include "algorithms/tonal/pitch2midi.h"
#include "algorithms/tonal/pitchcontours.h"
#include "algorithms/tonal/pitchcontoursegmentation.h"
#include "algorithms/tonal/pitchcontoursmelody.h"
#include "algorithms/tonal/pitchcontoursmonomelody.h"
#include "algorithms/tonal/pitchcontoursmultimelody.h"
#include "algorithms/tonal/pitchfilter.h"
#include "algorithms/tonal/pitchmelodia.h"
#include "algorithms/tonal/pitchsaliencefunction.h"
#include "algorithms/tonal/pitchsaliencefunctionpeaks.h"
#include "algorithms/tonal/pitchyin.h"
#include "algorithms/tonal/pitchyinfft.h"
#include "algorithms/tonal/pitchyinprobabilistic.h"
#include "algorithms/tonal/pitchyinprobabilities.h"
#include "algorithms/tonal/pitchyinprobabilitieshmm.h"
#include "algorithms/tonal/predominantpitchmelodia.h"
#include "algorithms/tonal/tonicindianartmusic.h"
#include "algorithms/tonal/tristimulus.h"
#include "algorithms/tonal/tuningfrequency.h"
#include "algorithms/tonal/vibrato.h"

namespace essentia {
namespace standard {

void registerAlgorithm() {
    AlgorithmFactory::Registrar<AutoCorrelation> regAutoCorrelation;
    AlgorithmFactory::Registrar<BinaryOperator> regBinaryOperator;
    AlgorithmFactory::Registrar<BinaryOperatorStream> regBinaryOperatorStream;
    AlgorithmFactory::Registrar<BPF> regBPF;
    AlgorithmFactory::Registrar<Chromagram> regChromagram;
    AlgorithmFactory::Registrar<Clipper> regClipper;
    AlgorithmFactory::Registrar<ConstantQ> regConstantQ;
    AlgorithmFactory::Registrar<CrossCorrelation> regCrossCorrelation;
    AlgorithmFactory::Registrar<CubicSpline> regCubicSpline;
    AlgorithmFactory::Registrar<DCT> regDCT;
    AlgorithmFactory::Registrar<Derivative> regDerivative;
    AlgorithmFactory::Registrar<Envelope> regEnvelope;
    AlgorithmFactory::Registrar<FFTK> regFFTK;
    AlgorithmFactory::Registrar<FFTKComplex> regFFTKComplex;
    AlgorithmFactory::Registrar<FrameBuffer> regFrameBuffer;
    AlgorithmFactory::Registrar<FrameCutter> regFrameCutter;
    AlgorithmFactory::Registrar<FrameToReal> regFrameToReal;
    AlgorithmFactory::Registrar<IDCT> regIDCT;
    AlgorithmFactory::Registrar<IFFTK> regIFFTK;
    AlgorithmFactory::Registrar<IFFTKComplex> regIFFTKComplex;
    AlgorithmFactory::Registrar<MaxFilter> regMaxFilter;
    AlgorithmFactory::Registrar<MinMax> regMinMax;
    AlgorithmFactory::Registrar<MonoMixer> regMonoMixer;
    AlgorithmFactory::Registrar<Multiplexer> regMultiplexer;
    AlgorithmFactory::Registrar<NoiseAdder> regNoiseAdder;
    AlgorithmFactory::Registrar<NSGConstantQ> regNSGConstantQ;
    AlgorithmFactory::Registrar<NSGIConstantQ> regNSGIConstantQ;
    AlgorithmFactory::Registrar<OverlapAdd> regOverlapAdd;
    AlgorithmFactory::Registrar<PeakDetection> regPeakDetection;
    AlgorithmFactory::Registrar<PowerSpectrum> regPowerSpectrum;
    AlgorithmFactory::Registrar<ReplayGain> regReplayGain;
    AlgorithmFactory::Registrar<Resample> regResample;
    AlgorithmFactory::Registrar<Scale> regScale;
    AlgorithmFactory::Registrar<SilenceRate> regSilenceRate;
    AlgorithmFactory::Registrar<Slicer> regSlicer;
    AlgorithmFactory::Registrar<Spectrum> regSpectrum;
    AlgorithmFactory::Registrar<SpectrumCQ> regSpectrumCQ;
    AlgorithmFactory::Registrar<Spline> regSpline;
    AlgorithmFactory::Registrar<StartStopSilence> regStartStopSilence;
    AlgorithmFactory::Registrar<StereoDemuxer> regStereoDemuxer;
    AlgorithmFactory::Registrar<StereoMuxer> regStereoMuxer;
    AlgorithmFactory::Registrar<StereoTrimmer> regStereoTrimmer;
    AlgorithmFactory::Registrar<Trimmer> regTrimmer;
    AlgorithmFactory::Registrar<UnaryOperator> regUnaryOperator;
    AlgorithmFactory::Registrar<UnaryOperatorStream> regUnaryOperatorStream;
    AlgorithmFactory::Registrar<Viterbi> regViterbi;
    AlgorithmFactory::Registrar<WarpedAutoCorrelation> regWarpedAutoCorrelation;
    AlgorithmFactory::Registrar<Welch> regWelch;
    AlgorithmFactory::Registrar<Windowing> regWindowing;
    AlgorithmFactory::Registrar<BarkBands> regBarkBands;
    AlgorithmFactory::Registrar<BFCC> regBFCC;
    AlgorithmFactory::Registrar<EnergyBand> regEnergyBand;
    AlgorithmFactory::Registrar<EnergyBandRatio> regEnergyBandRatio;
    AlgorithmFactory::Registrar<ERBBands> regERBBands;
    AlgorithmFactory::Registrar<FlatnessDB> regFlatnessDB;
    AlgorithmFactory::Registrar<Flux> regFlux;
    AlgorithmFactory::Registrar<FrequencyBands> regFrequencyBands;
    AlgorithmFactory::Registrar<GFCC> regGFCC;
    AlgorithmFactory::Registrar<HFC> regHFC;
    AlgorithmFactory::Registrar<HPCP> regHPCP;
    AlgorithmFactory::Registrar<LogSpectrum> regLogSpectrum;
    AlgorithmFactory::Registrar<MaxMagFreq> regMaxMagFreq;
    AlgorithmFactory::Registrar<MelBands> regMelBands;
    AlgorithmFactory::Registrar<MFCC> regMFCC;
    AlgorithmFactory::Registrar<Panning> regPanning;
    AlgorithmFactory::Registrar<RollOff> regRollOff;
    AlgorithmFactory::Registrar<SpectralCentroidTime> regSpectralCentroidTime;
    AlgorithmFactory::Registrar<SpectralComplexity> regSpectralComplexity;
    AlgorithmFactory::Registrar<SpectralContrast> regSpectralContrast;
    AlgorithmFactory::Registrar<SpectralPeaks> regSpectralPeaks;
    AlgorithmFactory::Registrar<SpectralWhitening> regSpectralWhitening;
    AlgorithmFactory::Registrar<SpectrumToCent> regSpectrumToCent;
    AlgorithmFactory::Registrar<StrongPeak> regStrongPeak;
    AlgorithmFactory::Registrar<TriangularBands> regTriangularBands;
    AlgorithmFactory::Registrar<TriangularBarkBands> regTriangularBarkBands;
    AlgorithmFactory::Registrar<Audio2Midi> regAudio2Midi;
    AlgorithmFactory::Registrar<Audio2Pitch> regAudio2Pitch;
    AlgorithmFactory::Registrar<ChordsDescriptors> regChordsDescriptors;
    AlgorithmFactory::Registrar<ChordsDetection> regChordsDetection;
    AlgorithmFactory::Registrar<ChordsDetectionBeats> regChordsDetectionBeats;
    AlgorithmFactory::Registrar<Dissonance> regDissonance;
    AlgorithmFactory::Registrar<HarmonicPeaks> regHarmonicPeaks;
    AlgorithmFactory::Registrar<HighResolutionFeatures> regHighResolutionFeatures;
    AlgorithmFactory::Registrar<Inharmonicity> regInharmonicity;
    AlgorithmFactory::Registrar<Key> regKey;
    AlgorithmFactory::Registrar<MultiPitchKlapuri> regMultiPitchKlapuri;
    AlgorithmFactory::Registrar<MultiPitchMelodia> regMultiPitchMelodia;
    AlgorithmFactory::Registrar<OddToEvenHarmonicEnergyRatio> regOddToEvenHarmonicEnergyRatio;
    AlgorithmFactory::Registrar<Pitch2Midi> regPitch2Midi;
    AlgorithmFactory::Registrar<PitchContours> regPitchContours;
    AlgorithmFactory::Registrar<PitchContourSegmentation> regPitchContourSegmentation;
    AlgorithmFactory::Registrar<PitchContoursMelody> regPitchContoursMelody;
    AlgorithmFactory::Registrar<PitchContoursMonoMelody> regPitchContoursMonoMelody;
    AlgorithmFactory::Registrar<PitchContoursMultiMelody> regPitchContoursMultiMelody;
    AlgorithmFactory::Registrar<PitchFilter> regPitchFilter;
    AlgorithmFactory::Registrar<PitchMelodia> regPitchMelodia;
    AlgorithmFactory::Registrar<PitchSalienceFunction> regPitchSalienceFunction;
    AlgorithmFactory::Registrar<PitchSalienceFunctionPeaks> regPitchSalienceFunctionPeaks;
    AlgorithmFactory::Registrar<PitchYin> regPitchYin;
    AlgorithmFactory::Registrar<PitchYinFFT> regPitchYinFFT;
    AlgorithmFactory::Registrar<PitchYinProbabilistic> regPitchYinProbabilistic;
    AlgorithmFactory::Registrar<PitchYinProbabilities> regPitchYinProbabilities;
    AlgorithmFactory::Registrar<PitchYinProbabilitiesHMM> regPitchYinProbabilitiesHMM;
    AlgorithmFactory::Registrar<PredominantPitchMelodia> regPredominantPitchMelodia;
    AlgorithmFactory::Registrar<TonicIndianArtMusic> regTonicIndianArtMusic;
    AlgorithmFactory::Registrar<Tristimulus> regTristimulus;
    AlgorithmFactory::Registrar<TuningFrequency> regTuningFrequency;
    AlgorithmFactory::Registrar<Vibrato> regVibrato;
    AlgorithmFactory::Registrar<BeatsLoudness> regBeatsLoudness;
    AlgorithmFactory::Registrar<BeatTrackerDegara> regBeatTrackerDegara;
    AlgorithmFactory::Registrar<BeatTrackerMultiFeature> regBeatTrackerMultiFeature;
    AlgorithmFactory::Registrar<BpmHistogram> regBpmHistogram;
    AlgorithmFactory::Registrar<BpmHistogramDescriptors> regBpmHistogramDescriptors;
    AlgorithmFactory::Registrar<BpmRubato> regBpmRubato;
    AlgorithmFactory::Registrar<HarmonicBpm> regHarmonicBpm;
    AlgorithmFactory::Registrar<LoopBpmConfidence> regLoopBpmConfidence;
    AlgorithmFactory::Registrar<LoopBpmEstimator> regLoopBpmEstimator;
    AlgorithmFactory::Registrar<NoveltyCurve> regNoveltyCurve;
    AlgorithmFactory::Registrar<NoveltyCurveFixedBpmEstimator> regNoveltyCurveFixedBpmEstimator;
    AlgorithmFactory::Registrar<OnsetDetection> regOnsetDetection;
    AlgorithmFactory::Registrar<OnsetDetectionGlobal> regOnsetDetectionGlobal;
    AlgorithmFactory::Registrar<OnsetRate> regOnsetRate;
    AlgorithmFactory::Registrar<Onsets> regOnsets;
    AlgorithmFactory::Registrar<PercivalBpmEstimator> regPercivalBpmEstimator;
    AlgorithmFactory::Registrar<PercivalEnhanceHarmonics> regPercivalEnhanceHarmonics;
    AlgorithmFactory::Registrar<PercivalEvaluatePulseTrains> regPercivalEvaluatePulseTrains;
    AlgorithmFactory::Registrar<RhythmExtractor> regRhythmExtractor;
    AlgorithmFactory::Registrar<RhythmExtractor2013> regRhythmExtractor2013;
    AlgorithmFactory::Registrar<RhythmTransform> regRhythmTransform;
    AlgorithmFactory::Registrar<SingleBeatLoudness> regSingleBeatLoudness;
    AlgorithmFactory::Registrar<SuperFluxExtractor> regSuperFluxExtractor;
    AlgorithmFactory::Registrar<SuperFluxNovelty> regSuperFluxNovelty;
    AlgorithmFactory::Registrar<SuperFluxPeaks> regSuperFluxPeaks;
    AlgorithmFactory::Registrar<TempoScaleBands> regTempoScaleBands;
    AlgorithmFactory::Registrar<TempoTap> regTempoTap;
    AlgorithmFactory::Registrar<TempoTapDegara> regTempoTapDegara;
    AlgorithmFactory::Registrar<TempoTapMaxAgreement> regTempoTapMaxAgreement;
    AlgorithmFactory::Registrar<TempoTapTicks> regTempoTapTicks;
    AlgorithmFactory::Registrar<Duration> regDuration;
    AlgorithmFactory::Registrar<EffectiveDuration> regEffectiveDuration;
    AlgorithmFactory::Registrar<Larm> regLarm;
    AlgorithmFactory::Registrar<Leq> regLeq;
    AlgorithmFactory::Registrar<Loudness> regLoudness;
    AlgorithmFactory::Registrar<LoudnessEBUR128> regLoudnessEBUR128;
    AlgorithmFactory::Registrar<LoudnessVickers> regLoudnessVickers;
    AlgorithmFactory::Registrar<LPC> regLPC;
    AlgorithmFactory::Registrar<ZeroCrossingRate> regZeroCrossingRate;
    AlgorithmFactory::Registrar<CentralMoments> regCentralMoments;
    AlgorithmFactory::Registrar<Centroid> regCentroid;
    AlgorithmFactory::Registrar<Crest> regCrest;
    AlgorithmFactory::Registrar<Decrease> regDecrease;
    AlgorithmFactory::Registrar<DistributionShape> regDistributionShape;
    AlgorithmFactory::Registrar<Energy> regEnergy;
    AlgorithmFactory::Registrar<Entropy> regEntropy;
    AlgorithmFactory::Registrar<Flatness> regFlatness;
    AlgorithmFactory::Registrar<GeometricMean> regGeometricMean;
    AlgorithmFactory::Registrar<Histogram> regHistogram;
    AlgorithmFactory::Registrar<InstantPower> regInstantPower;
    AlgorithmFactory::Registrar<Mean> regMean;
    AlgorithmFactory::Registrar<Median> regMedian;
    AlgorithmFactory::Registrar<PoolAggregator> regPoolAggregator;
    AlgorithmFactory::Registrar<PowerMean> regPowerMean;
    AlgorithmFactory::Registrar<RawMoments> regRawMoments;
    AlgorithmFactory::Registrar<RMS> regRMS;
    AlgorithmFactory::Registrar<SingleGaussian> regSingleGaussian;
    AlgorithmFactory::Registrar<Variance> regVariance;
    AlgorithmFactory::Registrar<CartesianToPolar> regCartesianToPolar;
    AlgorithmFactory::Registrar<Magnitude> regMagnitude;
    AlgorithmFactory::Registrar<PolarToCartesian> regPolarToCartesian;
    AlgorithmFactory::Registrar<AllPass> regAllPass;
    AlgorithmFactory::Registrar<BandPass> regBandPass;
    AlgorithmFactory::Registrar<BandReject> regBandReject;
    AlgorithmFactory::Registrar<DCRemoval> regDCRemoval;
    AlgorithmFactory::Registrar<EqualLoudness> regEqualLoudness;
    AlgorithmFactory::Registrar<HighPass> regHighPass;
    AlgorithmFactory::Registrar<IIR> regIIR;
    AlgorithmFactory::Registrar<LowPass> regLowPass;
    AlgorithmFactory::Registrar<MedianFilter> regMedianFilter;
    AlgorithmFactory::Registrar<MovingAverage> regMovingAverage;
}

} // namespace standard

namespace streaming {

void registerAlgorithm() {
    AlgorithmFactory::Registrar<AutoCorrelation, standard::AutoCorrelation> regAutoCorrelation;
    AlgorithmFactory::Registrar<BinaryOperator, standard::BinaryOperator> regBinaryOperator;
    AlgorithmFactory::Registrar<BinaryOperatorStream, standard::BinaryOperatorStream> regBinaryOperatorStream;
    AlgorithmFactory::Registrar<BPF, standard::BPF> regBPF;
    AlgorithmFactory::Registrar<Chromagram, standard::Chromagram> regChromagram;
    AlgorithmFactory::Registrar<Clipper, standard::Clipper> regClipper;
    AlgorithmFactory::Registrar<ConstantQ, standard::ConstantQ> regConstantQ;
    AlgorithmFactory::Registrar<CrossCorrelation, standard::CrossCorrelation> regCrossCorrelation;
    AlgorithmFactory::Registrar<CubicSpline, standard::CubicSpline> regCubicSpline;
    AlgorithmFactory::Registrar<DCT, standard::DCT> regDCT;
    AlgorithmFactory::Registrar<Derivative, standard::Derivative> regDerivative;
    AlgorithmFactory::Registrar<Envelope, standard::Envelope> regEnvelope;
    AlgorithmFactory::Registrar<FFTK, standard::FFTK> regFFTK;
    AlgorithmFactory::Registrar<FFTKComplex, standard::FFTKComplex> regFFTKComplex;
    AlgorithmFactory::Registrar<FrameBuffer, standard::FrameBuffer> regFrameBuffer;
    AlgorithmFactory::Registrar<FrameCutter, standard::FrameCutter> regFrameCutter;
    AlgorithmFactory::Registrar<FrameToReal, standard::FrameToReal> regFrameToReal;
    AlgorithmFactory::Registrar<IDCT, standard::IDCT> regIDCT;
    AlgorithmFactory::Registrar<IFFTK, standard::IFFTK> regIFFTK;
    AlgorithmFactory::Registrar<IFFTKComplex, standard::IFFTKComplex> regIFFTKComplex;
    AlgorithmFactory::Registrar<MaxFilter, standard::MaxFilter> regMaxFilter;
    AlgorithmFactory::Registrar<MinMax, standard::MinMax> regMinMax;
    AlgorithmFactory::Registrar<MonoMixer, standard::MonoMixer> regMonoMixer;
    AlgorithmFactory::Registrar<Multiplexer, standard::Multiplexer> regMultiplexer;
    AlgorithmFactory::Registrar<NoiseAdder, standard::NoiseAdder> regNoiseAdder;
    AlgorithmFactory::Registrar<NSGConstantQ, standard::NSGConstantQ> regNSGConstantQ;
    AlgorithmFactory::Registrar<NSGIConstantQ, standard::NSGIConstantQ> regNSGIConstantQ;
    AlgorithmFactory::Registrar<OverlapAdd, standard::OverlapAdd> regOverlapAdd;
    AlgorithmFactory::Registrar<PeakDetection, standard::PeakDetection> regPeakDetection;
    AlgorithmFactory::Registrar<PowerSpectrum, standard::PowerSpectrum> regPowerSpectrum;
    AlgorithmFactory::Registrar<RealAccumulator> regRealAccumulator;
    AlgorithmFactory::Registrar<ReplayGain, standard::ReplayGain> regReplayGain;
    AlgorithmFactory::Registrar<Scale, standard::Scale> regScale;
    AlgorithmFactory::Registrar<SilenceRate, standard::SilenceRate> regSilenceRate;
    AlgorithmFactory::Registrar<Slicer, standard::Slicer> regSlicer;
    AlgorithmFactory::Registrar<Spectrum, standard::Spectrum> regSpectrum;
    AlgorithmFactory::Registrar<SpectrumCQ, standard::SpectrumCQ> regSpectrumCQ;
    AlgorithmFactory::Registrar<Spline, standard::Spline> regSpline;
    AlgorithmFactory::Registrar<StartStopSilence, standard::StartStopSilence> regStartStopSilence;
    AlgorithmFactory::Registrar<StereoDemuxer, standard::StereoDemuxer> regStereoDemuxer;
    AlgorithmFactory::Registrar<StereoMuxer, standard::StereoMuxer> regStereoMuxer;
    AlgorithmFactory::Registrar<StereoTrimmer, standard::StereoTrimmer> regStereoTrimmer;
    AlgorithmFactory::Registrar<Trimmer, standard::Trimmer> regTrimmer;
    AlgorithmFactory::Registrar<UnaryOperator, standard::UnaryOperator> regUnaryOperator;
    AlgorithmFactory::Registrar<UnaryOperatorStream, standard::UnaryOperatorStream> regUnaryOperatorStream;
    AlgorithmFactory::Registrar<VectorRealAccumulator> regVectorRealAccumulator;
    AlgorithmFactory::Registrar<Viterbi, standard::Viterbi> regViterbi;
    AlgorithmFactory::Registrar<WarpedAutoCorrelation, standard::WarpedAutoCorrelation> regWarpedAutoCorrelation;
    AlgorithmFactory::Registrar<Welch, standard::Welch> regWelch;
    AlgorithmFactory::Registrar<Windowing, standard::Windowing> regWindowing;
    AlgorithmFactory::Registrar<BarkBands, standard::BarkBands> regBarkBands;
    AlgorithmFactory::Registrar<BFCC, standard::BFCC> regBFCC;
    AlgorithmFactory::Registrar<EnergyBand, standard::EnergyBand> regEnergyBand;
    AlgorithmFactory::Registrar<EnergyBandRatio, standard::EnergyBandRatio> regEnergyBandRatio;
    AlgorithmFactory::Registrar<ERBBands, standard::ERBBands> regERBBands;
    AlgorithmFactory::Registrar<FlatnessDB, standard::FlatnessDB> regFlatnessDB;
    AlgorithmFactory::Registrar<Flux, standard::Flux> regFlux;
    AlgorithmFactory::Registrar<FrequencyBands, standard::FrequencyBands> regFrequencyBands;
    AlgorithmFactory::Registrar<GFCC, standard::GFCC> regGFCC;
    AlgorithmFactory::Registrar<HFC, standard::HFC> regHFC;
    AlgorithmFactory::Registrar<HPCP, standard::HPCP> regHPCP;
    AlgorithmFactory::Registrar<LogSpectrum, standard::LogSpectrum> regLogSpectrum;
    AlgorithmFactory::Registrar<MaxMagFreq, standard::MaxMagFreq> regMaxMagFreq;
    AlgorithmFactory::Registrar<MelBands, standard::MelBands> regMelBands;
    AlgorithmFactory::Registrar<MFCC, standard::MFCC> regMFCC;
    AlgorithmFactory::Registrar<Panning, standard::Panning> regPanning;
    AlgorithmFactory::Registrar<RollOff, standard::RollOff> regRollOff;
    AlgorithmFactory::Registrar<SpectralCentroidTime, standard::SpectralCentroidTime> regSpectralCentroidTime;
    AlgorithmFactory::Registrar<SpectralComplexity, standard::SpectralComplexity> regSpectralComplexity;
    AlgorithmFactory::Registrar<SpectralContrast, standard::SpectralContrast> regSpectralContrast;
    AlgorithmFactory::Registrar<SpectralPeaks, standard::SpectralPeaks> regSpectralPeaks;
    AlgorithmFactory::Registrar<SpectralWhitening, standard::SpectralWhitening> regSpectralWhitening;
    AlgorithmFactory::Registrar<SpectrumToCent, standard::SpectrumToCent> regSpectrumToCent;
    AlgorithmFactory::Registrar<StrongPeak, standard::StrongPeak> regStrongPeak;
    AlgorithmFactory::Registrar<TriangularBands, standard::TriangularBands> regTriangularBands;
    AlgorithmFactory::Registrar<TriangularBarkBands, standard::TriangularBarkBands> regTriangularBarkBands;
    AlgorithmFactory::Registrar<ChordsDescriptors, standard::ChordsDescriptors> regChordsDescriptors;
    AlgorithmFactory::Registrar<ChordsDetection, standard::ChordsDetection> regChordsDetection;
    AlgorithmFactory::Registrar<Dissonance, standard::Dissonance> regDissonance;
    AlgorithmFactory::Registrar<HarmonicPeaks, standard::HarmonicPeaks> regHarmonicPeaks;
    AlgorithmFactory::Registrar<HighResolutionFeatures, standard::HighResolutionFeatures> regHighResolutionFeatures;
    AlgorithmFactory::Registrar<Inharmonicity, standard::Inharmonicity> regInharmonicity;
    AlgorithmFactory::Registrar<Key, standard::Key> regKey;
    AlgorithmFactory::Registrar<MultiPitchMelodia, standard::MultiPitchMelodia> regMultiPitchMelodia;
    AlgorithmFactory::Registrar<OddToEvenHarmonicEnergyRatio, standard::OddToEvenHarmonicEnergyRatio> regOddToEvenHarmonicEnergyRatio;
    AlgorithmFactory::Registrar<PitchContours, standard::PitchContours> regPitchContours;
    AlgorithmFactory::Registrar<PitchContoursMelody, standard::PitchContoursMelody> regPitchContoursMelody;
    AlgorithmFactory::Registrar<PitchContoursMonoMelody, standard::PitchContoursMonoMelody> regPitchContoursMonoMelody;
    AlgorithmFactory::Registrar<PitchContoursMultiMelody, standard::PitchContoursMultiMelody> regPitchContoursMultiMelody;
    AlgorithmFactory::Registrar<PitchFilter, standard::PitchFilter> regPitchFilter;
    AlgorithmFactory::Registrar<PitchMelodia, standard::PitchMelodia> regPitchMelodia;
    AlgorithmFactory::Registrar<PitchSalienceFunction, standard::PitchSalienceFunction> regPitchSalienceFunction;
    AlgorithmFactory::Registrar<PitchSalienceFunctionPeaks, standard::PitchSalienceFunctionPeaks> regPitchSalienceFunctionPeaks;
    AlgorithmFactory::Registrar<PitchYin, standard::PitchYin> regPitchYin;
    AlgorithmFactory::Registrar<PitchYinFFT, standard::PitchYinFFT> regPitchYinFFT;
    AlgorithmFactory::Registrar<PitchYinProbabilistic, standard::PitchYinProbabilistic> regPitchYinProbabilistic;
    AlgorithmFactory::Registrar<PitchYinProbabilities, standard::PitchYinProbabilities> regPitchYinProbabilities;
    AlgorithmFactory::Registrar<PitchYinProbabilitiesHMM, standard::PitchYinProbabilitiesHMM> regPitchYinProbabilitiesHMM;
    AlgorithmFactory::Registrar<PredominantPitchMelodia, standard::PredominantPitchMelodia> regPredominantPitchMelodia;
    AlgorithmFactory::Registrar<Tristimulus, standard::Tristimulus> regTristimulus;
    AlgorithmFactory::Registrar<TuningFrequency, standard::TuningFrequency> regTuningFrequency;
    AlgorithmFactory::Registrar<Vibrato, standard::Vibrato> regVibrato;
    AlgorithmFactory::Registrar<BeatsLoudness, standard::BeatsLoudness> regBeatsLoudness;
    AlgorithmFactory::Registrar<BeatTrackerDegara, standard::BeatTrackerDegara> regBeatTrackerDegara;
    AlgorithmFactory::Registrar<BeatTrackerMultiFeature, standard::BeatTrackerMultiFeature> regBeatTrackerMultiFeature;
    AlgorithmFactory::Registrar<BpmHistogram, standard::BpmHistogram> regBpmHistogram;
    AlgorithmFactory::Registrar<BpmHistogramDescriptors, standard::BpmHistogramDescriptors> regBpmHistogramDescriptors;
    AlgorithmFactory::Registrar<BpmRubato, standard::BpmRubato> regBpmRubato;
    AlgorithmFactory::Registrar<HarmonicBpm, standard::HarmonicBpm> regHarmonicBpm;
    AlgorithmFactory::Registrar<LoopBpmConfidence, standard::LoopBpmConfidence> regLoopBpmConfidence;
    AlgorithmFactory::Registrar<LoopBpmEstimator, standard::LoopBpmEstimator> regLoopBpmEstimator;
    AlgorithmFactory::Registrar<NoveltyCurve, standard::NoveltyCurve> regNoveltyCurve;
    AlgorithmFactory::Registrar<OnsetDetection, standard::OnsetDetection> regOnsetDetection;
    AlgorithmFactory::Registrar<OnsetDetectionGlobal, standard::OnsetDetectionGlobal> regOnsetDetectionGlobal;
    AlgorithmFactory::Registrar<OnsetRate, standard::OnsetRate> regOnsetRate;
    AlgorithmFactory::Registrar<Onsets, standard::Onsets> regOnsets;
    AlgorithmFactory::Registrar<PercivalBpmEstimator, standard::PercivalBpmEstimator> regPercivalBpmEstimator;
    AlgorithmFactory::Registrar<PercivalEnhanceHarmonics, standard::PercivalEnhanceHarmonics> regPercivalEnhanceHarmonics;
    AlgorithmFactory::Registrar<PercivalEvaluatePulseTrains, standard::PercivalEvaluatePulseTrains> regPercivalEvaluatePulseTrains;
    AlgorithmFactory::Registrar<RhythmExtractor, standard::RhythmExtractor> regRhythmExtractor;
    AlgorithmFactory::Registrar<RhythmExtractor2013, standard::RhythmExtractor2013> regRhythmExtractor2013;
    AlgorithmFactory::Registrar<RhythmTransform, standard::RhythmTransform> regRhythmTransform;
    AlgorithmFactory::Registrar<SingleBeatLoudness, standard::SingleBeatLoudness> regSingleBeatLoudness;
    AlgorithmFactory::Registrar<SuperFluxExtractor, standard::SuperFluxExtractor> regSuperFluxExtractor;
    AlgorithmFactory::Registrar<SuperFluxNovelty, standard::SuperFluxNovelty> regSuperFluxNovelty;
    AlgorithmFactory::Registrar<TempoScaleBands, standard::TempoScaleBands> regTempoScaleBands;
    AlgorithmFactory::Registrar<TempoTap, standard::TempoTap> regTempoTap;
    AlgorithmFactory::Registrar<TempoTapDegara, standard::TempoTapDegara> regTempoTapDegara;
    AlgorithmFactory::Registrar<TempoTapMaxAgreement, standard::TempoTapMaxAgreement> regTempoTapMaxAgreement;
    AlgorithmFactory::Registrar<TempoTapTicks, standard::TempoTapTicks> regTempoTapTicks;
    AlgorithmFactory::Registrar<EffectiveDuration, standard::EffectiveDuration> regEffectiveDuration;
    AlgorithmFactory::Registrar<Larm, standard::Larm> regLarm;
    AlgorithmFactory::Registrar<Loudness, standard::Loudness> regLoudness;
    AlgorithmFactory::Registrar<LoudnessEBUR128, standard::LoudnessEBUR128> regLoudnessEBUR128;
    AlgorithmFactory::Registrar<LoudnessEBUR128Filter> regLoudnessEBUR128Filter;
    AlgorithmFactory::Registrar<LoudnessVickers, standard::LoudnessVickers> regLoudnessVickers;
    AlgorithmFactory::Registrar<LPC, standard::LPC> regLPC;
    AlgorithmFactory::Registrar<ZeroCrossingRate, standard::ZeroCrossingRate> regZeroCrossingRate;
    AlgorithmFactory::Registrar<CentralMoments, standard::CentralMoments> regCentralMoments;
    AlgorithmFactory::Registrar<Centroid, standard::Centroid> regCentroid;
    AlgorithmFactory::Registrar<Crest, standard::Crest> regCrest;
    AlgorithmFactory::Registrar<Decrease, standard::Decrease> regDecrease;
    AlgorithmFactory::Registrar<DistributionShape, standard::DistributionShape> regDistributionShape;
    AlgorithmFactory::Registrar<Energy, standard::Energy> regEnergy;
    AlgorithmFactory::Registrar<Entropy, standard::Entropy> regEntropy;
    AlgorithmFactory::Registrar<Flatness, standard::Flatness> regFlatness;
    AlgorithmFactory::Registrar<GeometricMean, standard::GeometricMean> regGeometricMean;
    AlgorithmFactory::Registrar<Histogram, standard::Histogram> regHistogram;
    AlgorithmFactory::Registrar<InstantPower, standard::InstantPower> regInstantPower;
    AlgorithmFactory::Registrar<Mean, standard::Mean> regMean;
    AlgorithmFactory::Registrar<Median, standard::Median> regMedian;
    AlgorithmFactory::Registrar<PoolAggregator, standard::PoolAggregator> regPoolAggregator;
    AlgorithmFactory::Registrar<PowerMean, standard::PowerMean> regPowerMean;
    AlgorithmFactory::Registrar<RawMoments, standard::RawMoments> regRawMoments;
    AlgorithmFactory::Registrar<RMS, standard::RMS> regRMS;
    AlgorithmFactory::Registrar<SingleGaussian, standard::SingleGaussian> regSingleGaussian;
    AlgorithmFactory::Registrar<Variance, standard::Variance> regVariance;
    AlgorithmFactory::Registrar<CartesianToPolar, standard::CartesianToPolar> regCartesianToPolar;
    AlgorithmFactory::Registrar<Magnitude, standard::Magnitude> regMagnitude;
    AlgorithmFactory::Registrar<PolarToCartesian, standard::PolarToCartesian> regPolarToCartesian;
    AlgorithmFactory::Registrar<AllPass, standard::AllPass> regAllPass;
    AlgorithmFactory::Registrar<BandPass, standard::BandPass> regBandPass;
    AlgorithmFactory::Registrar<BandReject, standard::BandReject> regBandReject;
    AlgorithmFactory::Registrar<DCRemoval, standard::DCRemoval> regDCRemoval;
    AlgorithmFactory::Registrar<EqualLoudness, standard::EqualLoudness> regEqualLoudness;
    AlgorithmFactory::Registrar<HighPass, standard::HighPass> regHighPass;
    AlgorithmFactory::Registrar<IIR, standard::IIR> regIIR;
    AlgorithmFactory::Registrar<LowPass, standard::LowPass> regLowPass;
    AlgorithmFactory::Registrar<MedianFilter, standard::MedianFilter> regMedianFilter;
    AlgorithmFactory::Registrar<MovingAverage, standard::MovingAverage> regMovingAverage;
}

} // namespace streaming

} // namespace essentia
